spring:
 application:
  name: "configserver"
 profiles:
  #active: native
  active: git
 cloud:
  config:
   server:
    #native:
     #search-locations: "classpath:/config"
     #search-locations: "file:///C://microservice-project-configs"
    git:
     uri: "https://github.com/LuciosGIT/microservice-project-configs-repo.git"
     default-label: main
     timeout: 5
     clone-on-start: true
     force-pull: true


management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
  readiness-state:
   enabled: true
  liveness-state:
   enabled: true
 endpoint:
  health:
   probes:
    enabled: true
 metrics:
  tags:
   application: ${spring.application.name}


encrypt:
 key: "1204712DNMAKLMKM219381"


server:
 port: 8071

logging:
 pattern:
  level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

